### ISSUE TITLE
Errors in measurements with the LV-MaxSonar EZ serie

### ISSUE THREAD

**Issue by maky-hnou** [alx-s/RPi_tutorials#1]
I used this code with a Raspberry Pi 3 model B and an MCP3008 and an LV-MaxSonar EZ2. The only difference is that I wired the VREF pin of the MCP3008 to the 3.3V pin of the raspberry (because I tried with the 5V pin, but it didn't work).
After running the script, I got a logical output. However, there was an error rate that grows with the distance between the sensor and the object.
The following examples explain the errors I got :

**An object that is 16 cm away from the sensor ----> the output is 21 cm
An object that is 17 cm away from the sensor ----> the output is 21 cm
An object that is 18 cm away from the sensor ----> the output is 21 cm
An object that is 19 cm away from the sensor ----> the output is 24 cm
An object that is 35 cm away from the sensor ----> the output is 42 cm
An object that is 56 cm away from the sensor ----> the output is 66 cm & 67cm
An object that is 70 cm away from the sensor ----> the output is 84 cm
An object that is 84 cm away from the sensor ----> the output is 96 cm**

I tried with many EZ2 sensors, but I still got the same errors.

Someone Has tried that or has any solution please?

**Comment by alx-s** [comment]
Hi Hani,
The VREF pin on the MCP3008 should have the same voltage as the Vcc pin of the sensor. It looks like you wired the maxbotix to +5v, which means that it will output an analog voltage mapped over 5V. In you case, the MCP3008 expects to measure a voltage between 0v and 3.3V. This explains why you read distances higher than the actual ones. Make sure you wire the ADC's VREF to the same voltage as the sensor's Vcc.
An other point, be careful with the definition of maxbotix, some go done to a centimeter, other to an inch. I don't remember which one I used in the tutorial. It looks like the one you use won't be more precise than an inch. Check their website to find the model that suits you needs
Best,
Alex

**Comment by maky-hnou** [comment]
This fixed the problem, thank you.
